# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nboGJDEudbAQf4zZoU8s43Gs92nAZtdH
"""

import streamlit as st
import pandas as pd
import ast
from fuzzywuzzy import process
from itertools import chain

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("movies_metadata.csv", low_memory=False)
    df['genre_list'] = df['genres'].apply(lambda g: extract_genres(g))
    return df

def extract_genres(genre_str):
    try:
        genres = ast.literal_eval(genre_str)
        return [g['name'] for g in genres]
    except:
        return []

def recommend_movie(genre_input, df):
    all_genres = sorted(set(chain.from_iterable(df['genre_list'])))
    best_match, score = process.extractOne(genre_input, all_genres)

    if score < 60:
        return None, f"No genre matched '{genre_input}'. Try: {', '.join(all_genres)}"

    filtered = df[df['genre_list'].apply(lambda x: best_match in x)]
    if filtered.empty:
        return None, f"No movies found in genre '{best_match}'."

    movie = filtered.sample(1).iloc[0]
    return {
        "🎬 Title": movie['title'],
        "🎯 Interpreted Genre": best_match,
        "📝 Overview": movie.get('overview', 'No description available.'),
        "⭐ Rating": movie.get('vote_average', 'N/A'),
        "📅 Release Date": movie.get('release_date', 'Unknown')
    }, None

# --- Streamlit App UI ---
st.set_page_config(page_title="🎥 Movie Recommender", page_icon="🎬")
st.title("🎥 Movie Recommender")
st.markdown("Enter any movie genre (e.g. *love story*, *sci-fi*, *funny*, *romantic*, etc.)")

genre_input = st.text_input("🎭 Genre", "")

if st.button("🎲 Recommend"):
    df = load_data()
    result, error = recommend_movie(genre_input, df)

    if error:
        st.warning(error)
    else:
        st.success(f"Here's a movie in the genre '{result['🎯 Interpreted Genre']}':")
        st.markdown(f"**{result['🎬 Title']}**")
        st.markdown(f"*Rating:* {result['⭐ Rating']} | *Release:* {result['📅 Release Date']}")
        st.markdown(f"**Overview:**\n{result['📝 Overview']}")

